# action.yml
name: 'ECS deploy'
description: 'Github action using fabfuel/ecs-deploy script for ecs deployments'
inputs:
    cluster:
        description: 'Cluster name where service/task will be deployed'
        required: true
    service:
        description: 'Service name of the service/task to be deployed'
        required: true
    task:
        description: 'Task definition name to be updated'
        required: false
    container:
        description: 'Container name to be updated'
        required: false
    envfile:
        description: 'Env file path'
        required: false
    timeout:
        description: 'Deployment timeout (default 300)'
        required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cluster }}
    - ${{ inputs.service }}
    - ${{ inputs.task }}
    - ${{ inputs.container }}
    - ${{ inputs.envfile }}
    - ${{ inputs.timeout }}